# Create a new profile
POST http://localhost:3000/profiles
Content-Type: application/json

{
  "username": "Sponge Bob",
  "age": 30,
  "bio": "Software engineer and open source enthusiast.",
  "vaccinated": true,
  "email": "spongebob@example.com",
  "password": "spongePass!2024"
}

### Get all profiles
GET http://localhost:3000/profiles

### Get all profiles with query parameters
GET http://localhost:3000/profiles?vaccinated=true&age=30

### Get a specific profile by ID
GET http://localhost:3000/profiles/{id}

### Update an existing profile by ID
PUT http://localhost:3000/profiles/{id}
Content-Type: application/json

{
  "username": "John Doe",
  "age": 31,
}

### Delete a profile by ID
DELETE http://localhost:3000/profiles/a016faab-1c10-4800-9ead-3812b171ebbf